//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsvViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CsvViewer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backslash.
        /// </summary>
        internal static string BACKSLACK {
            get {
                return ResourceManager.GetString("BACKSLACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string COLUMN {
            get {
                return ResourceManager.GetString("COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLS.
        /// </summary>
        internal static string COLUMNS {
            get {
                return ResourceManager.GetString("COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma.
        /// </summary>
        internal static string COMMA {
            get {
                return ResourceManager.GetString("COMMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Symbol.
        /// </summary>
        internal static string COMMENT {
            get {
                return ResourceManager.GetString("COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string CONFIRM {
            get {
                return ResourceManager.GetString("CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csv file (*.csv).
        /// </summary>
        internal static string CSV_FILE {
            get {
                return ResourceManager.GetString("CSV_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter.
        /// </summary>
        internal static string DELIMITER {
            get {
                return ResourceManager.GetString("DELIMITER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot.
        /// </summary>
        internal static string DOT {
            get {
                return ResourceManager.GetString("DOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dubbeel aanhalingstekens.
        /// </summary>
        internal static string DOUBLE_QUOTE {
            get {
                return ResourceManager.GetString("DOUBLE_QUOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter column.
        /// </summary>
        internal static string FILTER_COLUMN {
            get {
                return ResourceManager.GetString("FILTER_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first line contains column names..
        /// </summary>
        internal static string HAS_COLUMN_LINE {
            get {
                return ResourceManager.GetString("HAS_COLUMN_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incides.
        /// </summary>
        internal static string INDICES {
            get {
                return ResourceManager.GetString("INDICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load complete.
        /// </summary>
        internal static string LOAD_COMPLETE {
            get {
                return ResourceManager.GetString("LOAD_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file.
        /// </summary>
        internal static string LOADING {
            get {
                return ResourceManager.GetString("LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No delimiter selected.
        /// </summary>
        internal static string NO_DELIMITER_SELECTED {
            get {
                return ResourceManager.GetString("NO_DELIMITER_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected.
        /// </summary>
        internal static string NO_FILE_SELECTED {
            get {
                return ResourceManager.GetString("NO_FILE_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        internal static string OPEN_FILE {
            get {
                return ResourceManager.GetString("OPEN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string OPTIONS {
            get {
                return ResourceManager.GetString("OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string PAGE {
            get {
                return ResourceManager.GetString("PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe.
        /// </summary>
        internal static string PIPE {
            get {
                return ResourceManager.GetString("PIPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanhalingsteken.
        /// </summary>
        internal static string QUOTE {
            get {
                return ResourceManager.GetString("QUOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string RESULT {
            get {
                return ResourceManager.GetString("RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROWS.
        /// </summary>
        internal static string ROWS {
            get {
                return ResourceManager.GetString("ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting a file..
        /// </summary>
        internal static string SELECTING_FILE {
            get {
                return ResourceManager.GetString("SELECTING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semicolon.
        /// </summary>
        internal static string SEMICOLON {
            get {
                return ResourceManager.GetString("SEMICOLON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string SIZE {
            get {
                return ResourceManager.GetString("SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will skip rows that start with &apos;{0}&apos;..
        /// </summary>
        internal static string SKIP_COMMENT_LINE {
            get {
                return ResourceManager.GetString("SKIP_COMMENT_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        internal static string TAB {
            get {
                return ResourceManager.GetString("TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text file (*.txt).
        /// </summary>
        internal static string TXT_FILE {
            get {
                return ResourceManager.GetString("TXT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve the csv file delimiter..
        /// </summary>
        internal static string UNABLE_TO_READ_DELIMITER {
            get {
                return ResourceManager.GetString("UNABLE_TO_READ_DELIMITER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating file options.
        /// </summary>
        internal static string UPDATING_OPTIONS {
            get {
                return ResourceManager.GetString("UPDATING_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string VIEW {
            get {
                return ResourceManager.GetString("VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View rows.
        /// </summary>
        internal static string VIEW_ROWS {
            get {
                return ResourceManager.GetString("VIEW_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewing.
        /// </summary>
        internal static string VIEWING {
            get {
                return ResourceManager.GetString("VIEWING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whitespace.
        /// </summary>
        internal static string WHITESPACE {
            get {
                return ResourceManager.GetString("WHITESPACE", resourceCulture);
            }
        }
    }
}
